// <auto-generated />
namespace PersonalFinanceTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createTransactionTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTransactionTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202406051356355_createTransactionTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
